### ISSUE TITLE
GetFeatureInfo

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wms-client13#1]
It seems that there is a problem with the test internally, because
GetFeatureInfo requests are never logged within the testrun and so the test is
passed at all without any note about the GFI tests.

Tested with  QGIS by Sebastian G.

GetFeatureInfo-Fehler Error downloading
http://cite.opengeospatial.org/te2/monitor/20?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&BBOX=-0.72065098468271349,-1.13946951327695367,1.11684901531728675,1.77073318942574987&CRS=EPSG:4326&WIDTH=1172&HEIGHT=740&LAYERS=cite:Bridges&STYLES=&FORMAT=image/png&QUERY_LAYERS=cite:Bridges&INFO_FORMAT=text/html&I=198&J=698&FEATURE_COUNT=10

server replied: Internal Server Error

[http://cite.opengeospatial.org/te2/monitor/20?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&BBOX=-0.72065098468271349,-1.13946951327695367,1.11684901531728675,1.77073318942574987&CRS=EPSG:4326&WIDTH=1172&HEIGHT=740&LAYERS=cite:Bridges&STYLES=&FORMAT=image/png&QUERY_LAYERS=cite:Bridges&INFO_FORMAT=text/html&I=198&J=698&FEATURE_COUNT=10]

**Comment by rjmartell** [comment]
I was not able to duplicate this issue using uDig 1.4.0 as the client with a local TE installation and the latest ETS revision. A GetFeatureInfo request was submitted to the proxy endpoint with the following query parameters:

`SERVICE=WMS&INFO_FORMAT=text/html&LAYERS=cite:BasicPolygons&CRS=CRS:84&FORMAT=image/png&HEIGHT=502&J=428&REQUEST=GetFeatureInfo&I=414&WIDTH=832&BBOX=-5.800796812749004,-1.0,5.800796812749004,6.0&STYLES=default&QUERY_LAYERS=cite%3ABasicPolygons&VERSION=1.3.0`

The request was deemed to be valid:

```
Test gfi:check-GetFeatureInfo-request type Mandatory default result Passed (s0007/d504e124_1_9)
Assertion: The client GetFeatureInfo request is valid.
Subtest name basic:mandatory-params type Mandatory path s0007/d504e124_1_9/d137e16_1 result Passed
Subtest name basic:version type Mandatory path s0007/d504e124_1_9/d137e70_1 result Passed
Subtest name basic:request type Mandatory path s0007/d504e124_1_9/d137e78_1 result Passed
Subtest name gm:core-map-request type Mandatory path s0007/d504e124_1_9/d137e87_1 result Passed
Subtest name gfi:query_layers-count type Mandatory path s0007/d504e124_1_9/d137e96_1 result Passed
Subtest name gfi:query_layers-values type Mandatory path s0007/d504e124_1_9/d137e101_1 result Passed
Subtest name gfi:query_layers-queryable type Mandatory path s0007/d504e124_1_9/d137e106_1 result Passed
Subtest name gfi:info_format type Mandatory path s0007/d504e124_1_9/d137e117_1 result Passed
Subtest name gfi:i type Mandatory path s0007/d504e124_1_9/d137e127_1 result Passed
Subtest name gfi:j type Mandatory path s0007/d504e124_1_9/d137e135_1 result Passed
Result: Passed
```

The (HTML) response entity was displayed in the 'Information' tab (see screenshot). However it seems that the embedded JavaScript was not processed by the client.

![udig-featureinfo](https://cloud.githubusercontent.com/assets/1653506/3616478/afcd214a-0dd3-11e4-808b-c981fe15bb73.png)

**Comment by rjmartell** [comment]
It seems that few--if any--WMS clients allow the user to select the (preferred?) content type of the GetFeatureInfo response (the INFO_FORMAT parameter is required). The target WMS [lists 12 supported formats](http://cite.lat-lon.de/deegree-webservices-3.3.6-2/services/wms?service=WMS&version=1.3.0&request=GetCapabilities); perhaps the client just chooses the first format it recognizes.

**Note**: The content of the GetFeatureInfo response is unspecified in WMS 1.3

**Comment by bermud** [comment]
This is not an issue any more in 1.0.
