### ISSUE TITLE
GetMap test has incorrect requirement for STYLES parameter

### ISSUE THREAD

**Issue by mpdaly** [opengeospatial/ets-wms-client13#14]
06-042 says, in section 7.3.3.4:

"If all layers are to be shown using the default style, either the form “STYLES=” or “STYLES=,,,” is valid."

However, the test suite rejects the following valid request (you will need to replace the {instance} in the URL with your own):

http://cite.opengeospatial.org/teamengine/monitor/{instance}?VERSION=1.3.0&SERVICE=WMS&REQUEST=GetMap&STYLES=&FORMAT=image%2fpng&CRS=CRS:84&LAYERS=cite:BasicPolygons&BBOX=-2,-1,2,6&WIDTH=473&HEIGHT=828&BGCOLOR=0xFFFFFF&EXCEPTIONS=XML

Changing the "STYLES=" KVP to "STYLES=default" gets a valid response.

**Comment by bermud** [comment]
@upendra-sachan, please take a look at this issue.

**Comment by upendra-sachan** [comment]
This issue occurred due to array size check was not present in https://github.com/opengeospatial/teamengine/blob/master/teamengine-web/src/main/java/com/occamlab/te/web/CoverageMonitor.java.
Now if user does not send any 'Style' it will handle it.
Changes have been done inside teamengine-web.
