### ISSUE TITLE
getmap:each-style Layer name(LaYeRs=Ponds) are not changed

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wms-client13#15]
The name of the layer do not change in the test. It should.

Reported in the forum
http://lists.opengeospatial.org/pipermail/cite-forum/2015-July/001513.html

ex 1)
Test getmap:each-style type Mandatory default result Passed (s0003/d711e387_1/d1794e54_1/d1794e317_2)
Assertion: For style &quot;BasicPolygons&quot;, when the STYLES parameter is set to that style name, the MIME type of the response is valid.
Request d1794e5551_1:
   Method: get
   URL: ...?&StYlEs=BasicPolygons&BbOx=-0.0025%2C-0.0025%2C0.0025%2C0.0025&CrS=CRS%3A84&LaYeRs=Ponds&WiDtH=100&VeRsIoN=1.3.0&FoRmAt=image%2Fpng&HeIgHt=100&ReQuEsT=GetMap

ex 2)
Test getmap:each-style type Mandatory default result Passed (s0003/d711e387_1/d1794e54_1/d1794e317_3)
Assertion: For style &quot;BuildingCenters&quot;, when the STYLES parameter is set to that style name, the MIME type of the response is valid.
Request d1794e5551_1:
   Method: get
   URL: ...?&StYlEs=BuildingCenters&BbOx=-0.0025%2C-0.0025%2C0.0025%2C0.0025&CrS=CRS%3A84&LaYeRs=Ponds&WiDtH=100&VeRsIoN=1.3.0&FoRmAt=image%2Fpng&HeIgHt=100&ReQuEsT=GetMap

ex 3)
Test getmap:each-style type Mandatory default result Passed (s0003/d711e387_1/d1794e54_1/d1794e317_4)
Assertion: For style &quot;Autos&quot;, when the STYLES parameter is set to that style name, the MIME type of the response is valid.
Request d1794e5551_1:
   Method: get
   URL: ...?&StYlEs=Autos&BbOx=-0.0025%2C-0.0025%2C0.0025%2C0.0025&CrS=CRS%3A84&LaYeRs=Ponds&WiDtH=100&VeRsIoN=1.3.0&FoRmAt=image%2Fpng&HeIgHt=100&ReQuEsT=GetMap

ex 4)
Test getmap:each-style type Mandatory default result Passed (s0003/d711e387_1/d1794e54_1/d1794e317_5)
Assertion: For style &quot;Forests&quot;, when the STYLES parameter is set to that style name, the MIME type of the response is valid.
Request d1794e5551_1:
   Method: get
   URL: ...?&StYlEs=Forests&BbOx=-0.0025%2C-0.0025%2C0.0025%2C0.0025&CrS=CRS%3A84&LaYeRs=Ponds&WiDtH=100&VeRsIoN=1.3.0&FoRmAt=image%2Fpng&HeIgHt=100&ReQuEsT=GetMap

**Comment by upendra-sachan** [comment]
In wms-client1.3 except to cite: Terrain layer, other layer sends their style in the form of default from wms-server.

**Comment by bermud** [comment]
The client should read the GetCapabilities and get the associated style to a particular layer to configure a proper map request. The test interacts with the reference implementation:
 http://cite.deegree.org/deegree-webservices-3.3.14-2/services/wms?service=WMS&version=1.3.0&request=GetCapabilities

The server advertises three styles for the cite:Terrain layer. All the other layers only use the default style.
