### ISSUE TITLE
server fails to parse all the requests.

### ISSUE THREAD

**Issue by vinnakota** [opengeospatial/ets-wms-client13#21]
When testing client requests not all requests are captured correctly by the server. I can see the valid request go through Fiddler.  
After I stop the test session the generated report says 16 passed and also list failures.
Attached a PDF of the test result.

[Test Session Results.pdf](https://github.com/opengeospatial/ets-wms-client13/files/431406/Test.Session.Results.pdf)

**Comment by bermud** [comment]
@vinnakota, Thank you for submitting the issue. We are investigating.
@keshav-nangare, It seems the front web page (green check marks) is not getting properly updated.

**Comment by keshavnangare** [comment]
@vinnakota 

Have tried with the latest teamengine and wms-client13 version?

Because I have tried with the latest version of teamengine(4.9-SNAPSHOT) and wms-client13(1.3-SNAPSHOT) with the "Udig" client, it was working fine,

Following is the result:

![test session results 4](https://cloud.githubusercontent.com/assets/14732650/18641924/4fceeea2-7ebc-11e6-837f-96022efe84af.png)

**Comment by vinnakota** [comment]
Hi Keshav,
 I am using ArcMap. The client sends correct requests (I verified using fiddler). I tried the latest available TeamEngine and am still seeing these issues.

**Comment by bermud** [comment]
We tested with ArcMap and the TEAM Engine beta installation http://cite.opengeospatial.org/te2/.
And it passes.

See this video:
http://cite.opengeospatial.org/pub/cite/files/te2_wms-client.mp4-20160922.zip

Are you using the production or beta web site?

**Comment by vinnakota** [comment]
I tried both the Production and Beta test engines. See failures in both of them.

[WmsClient_TeamEngine_Beta.pdf](https://github.com/opengeospatial/ets-wms-client13/files/543128/WmsClient_TeamEngine_Beta.pdf)
[WmsClient_TeamEngine_Prodcution.pdf](https://github.com/opengeospatial/ets-wms-client13/files/543127/WmsClient_TeamEngine_Prodcution.pdf)

**Comment by lgoltz** [comment]
May be related to #24.

**Comment by lgoltz** [comment]
A new version of the ETS WMS Client 1.3 was installed on beta with some bug fixes related to the described problem.
@vinnakota Can you recheck on [beta](http://cite.opengeospatial.org/te2/)?

**Comment by vinnakota** [comment]
@lgoltz the new version on Beta is much better. The test engine expects a request for cite:terrain layer that does not exist in the capabilities causing one test to fail.
another minor issue: the test engine seems to parse only the first layer in a GetMap request. Because of this I have to toggle each layer visibility individually for the parser to recognize the requests being sent.

**Comment by lgoltz** [comment]
@vinnakota Thanks for quick response! The problem with the layer cite:Terrain is already documented in #32. I've created  a new issue for the other one: #34
