### ISSUE TITLE
Not able to see more details about a failure

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wms-client13#22]
Then testing WMS Client Test Suite  1.2 using Team Engine 4.10. The session results as shown below. It is not possible to get more information regarding the failed test cases. 
![client](https://cloud.githubusercontent.com/assets/3738898/22977023/1779a196-f35b-11e6-8181-51a676073dbd.png)

Logs here: 
http://cite.opengeospatial.org/pub/cite/files/s0011-20170215.zip

**Comment by bermud** [comment]
@keshav-nangare,  Please review the logs and explain why the client failed and try with dig and check if you have a similar experience

**Comment by bermud** [comment]
Will move this issue to waiting status until we figure out how to replicate it.

**Comment by lgoltz** [comment]
Duplicate of #27
