### ISSUE TITLE
Update CTL with better information about conformance classes 

### ISSUE THREAD

**Issue by keshavnangare** [opengeospatial/ets-wms-client13#23]
The test needs to be updated to better provide information about the grouping of the conformance class and determination about which ones are the basic conformance classes needed for certification.

Changes that are required are described here:

https://github.com/opengeospatial/cite/wiki/Encoding-Conformance-Classes

**Comment by lgoltz** [comment]
I think all tests except GetFeatureInfo have to be declared as cc and basic.

**Comment by lgoltz** [comment]
As far as I  see  with the current structure of the tests the conformance classes cannot be configured. @keshav-nangare  Do you have an idea?

**Comment by keshavnangare** [comment]
Teamengine failed to generate new HTML report after CC configuration due to the empty test-inputs, so creating a new issue in teamengine section.

**Comment by dstenger** [comment]
Configuration of CCs must still be done.

**Comment by lgoltz** [comment]
> Teamengine failed to generate new HTML report after CC configuration due to the empty test-inputs, so creating a new issue in teamengine section.

After merging https://github.com/opengeospatial/teamengine/pull/349 the new HTML report is available.

**Comment by lgoltz** [comment]
Tested locally with Docker environment (with current teamengine SNAPSHOT and ETS branch feature-issue#23) and QGIS 3.4 the new HTML report does not match the old report. 
The **old report** is fine (the selected layers are marked as passed): 

![ets-wms-client13-23_oldreport](https://user-images.githubusercontent.com/3007848/48194958-bba66a80-e34e-11e8-9ec3-7bd4e031dc9b.png)

But in the **new HTML report** all tests are passed:

![ets-wms-client13-23_htmlreport](https://user-images.githubusercontent.com/3007848/48195025-e5f82800-e34e-11e8-85ee-71e8b4a22036.png)

**Comment by dstenger** [comment]
Workaround: Disable new HTML report and introduce same behaviour occurring when basic conformance classes are not configured.

**Comment by keshavnangare** [comment]
@dstenger 

The PR https://github.com/opengeospatial/ets-wms-client13/pull/39  contains the basic CC configurationis and it's not merged into master.
If we not merging this PR then it will work as we are expecting in previous comment. We can keep this PR in waiting or close for now.
