### ISSUE TITLE
The WMS client test fails to capture all GetMap requests

### ISSUE THREAD

**Issue by robinhoutmeyers** [opengeospatial/ets-wms-client13#24]
While using the WMS client test, we noticed that it does not capture all WMS GetMap requests. It seems that it stops after +- 2 requests. However, the server does seem to work ok, because we can retrieve and visualize all WMS layers in our client. Based on this, I would guess an issue in the monitoring logic.

Example of the observed behavior:

![wms_client_test_behavior](https://user-images.githubusercontent.com/11718993/27093693-ff16a512-5067-11e7-87bf-cc8dd70cc81c.png)

No matter how many times I retrieve all layers (with different bounding boxes, image formats, 1 layer at a time vs multiple, etc.), it stays like this.

**Comment by lgoltz** [comment]
Tested with the following settings:
 * local Docker environment
 * ets-wms-client13 1.3-SNAPSHOT
 * TEAM Engine 5.2-SNAPSHOT
 * Firefox Quantum 57.0.4 (64-Bit)
 * Testes client: QGIS 2.18.15

The problem still occurs. 

The  request send  in https://github.com/opengeospatial/ets-wms-client13/blob/48e27d336e22474c1af65e7c0552634aa531b4dc/src/main/scripts/ctl/main.ctl#L681-L683 returns exact one line:
```
{"TEST":[{"Name":"cite:Autos"}]}
```

The request is handled by the method https://github.com/opengeospatial/ets-wms-client13/blob/48e27d336e22474c1af65e7c0552634aa531b4dc/src/main/java/com/occamlab/te/spi/jaxrs/resources/wmsclient/TestMapResources.java#L53

The layers are read from the file test_data/Get-Map-Layer.xml in the directory of the session.

It seems it is expected that the response contains all of the requested layers as the index will be increased by if a known layer is found. https://github.com/opengeospatial/ets-wms-client13/blob/48e27d336e22474c1af65e7c0552634aa531b4dc/src/main/scripts/ctl/main.ctl#L685

As the response contains only one layer but expected are all layers with the results, this causes an undefined entry and the result is not updated as expected: https://github.com/opengeospatial/ets-wms-client13/blob/48e27d336e22474c1af65e7c0552634aa531b4dc/src/main/scripts/ctl/main.ctl#L696

**Comment by keshavnangare** [comment]
Fixed with this commit: 85a15893e426481fc1c9f9b243febbef7295d0a9.  [PR: #31]
