### ISSUE TITLE
Test fails even though subtests are passed

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wms-client13#25]
Testing the WMS Client on ZuluGIS 8.0 [1] with WMS 1.3 client on the official TEAM Engine [1] fails even though all test are successful. 

![wmstest](https://user-images.githubusercontent.com/3007848/32594813-bc10f886-c52d-11e7-8417-9b2304e9780b.png)

Output of the console: [Console.html.zip](https://github.com/opengeospatial/ets-wms-client13/files/1456824/Console.html.zip)

[1] http://www.opengeospatial.org/resource/products/details/?pid=1422
[2] http://cite.opengeospatial.org/teamengine/

**Comment by lgoltz** [comment]
The exported session does not contain any more information about a failure.

Does the problem occurs with the beta version of the TEAM Engine [1]?

[1] http://cite.opengeospatial.org/te2/

**Comment by lgoltz** [comment]
On beta the same problem occurred than on alpha. 

From the log files on the server I cannot find any hints.

**Comment by lgoltz** [comment]
The problem seems to be that the test results are not correctly mapped in the execution page:
![image](https://user-images.githubusercontent.com/3007848/32892178-a2a67508-cad5-11e7-94de-5b1630db1c27.png)

E.g. the test `cite:Bridges` is executed and successful, but the result is not shown in the execution page. During execution of the test, the result is logged as expected in the console and is declared as passed. The tree view is equivalent to the execution page, before the test was stopped.

**Comment by lgoltz** [comment]
The failure can be reproduced locally with the docker environment and QGIS.

**Comment by lgoltz** [comment]
A new version of the ETS WMS Client 1.3 was installed on beta with some bug fixes related to the described problem.

ZuluGIS 8.0 should be rechecked.

**Comment by dstenger** [comment]
ZuluGIS 8.0 was rechecked and reported problem does not occur any more.
