### ISSUE TITLE
Result view (tree) is missing

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wms-client13#27]
After stopping the test the result view is missing. Only the table with the test results are available. The following stack trace is logged in the tomcat log:

```
Nov 16, 2017 1:08:19 PM org.apache.catalina.core.StandardWrapperValve invoke
SEVERE: Servlet.service() for servlet [TestSuiteController] in context with path [/teamengine] threw exception [java.io.FileNotFoundException: /root/te_base/users/lgoltz/s0036/test_data/finalResult.txt (No such file or directory)] with root cause
java.io.FileNotFoundException: /root/te_base/users/lgoltz/s0036/test_data/finalResult.txt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at com.occamlab.te.spi.jaxrs.resources.wmsclient.TestFinalResult.handleGet(TestFinalResult.java:46)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
```

Tested with
 * local docker environment (as well as in production)
 * TEAM Engine 4.10 
 *  ETS Web Map Service 1.3 (WMS) - Client 1.2

**Comment by keshavnangare** [comment]
The result tree is not visible in the latest teamengine version. While implementing the new HTML report we commented code which is showing the wms-client result so thats the reason missing result tree.

I will update the teamengine which will display the wms-client result on the old result page.

**Comment by lgoltz** [comment]
I've tested the branch https://github.com/opengeospatial/ets-wms-client13/tree/feature-isssue%2328 (PR #30) with the TEAM Engine branch https://github.com/opengeospatial/teamengine/tree/feature-issue%23304 (PR https://github.com/opengeospatial/teamengine/pull/305). 
The exception still occurs and the result is empty. After stopping the test the information that the new HTML report is not available is shown:

![newhtmlreportnotavailable](https://user-images.githubusercontent.com/3007848/34824171-b22dfb30-f6cd-11e7-850f-4d996d2ea5f8.png)

The 'detailed old test report' looks like:  
![missingdetails](https://user-images.githubusercontent.com/3007848/34824138-891af22a-f6cd-11e7-9929-7df4799bebfa.png)

The file /root/te_base/users/lgoltz/s0008/test_data/finalResult.txt does not exist.

**Comment by lgoltz** [comment]
Result tree is still  missing, cause of the failure described in https://github.com/opengeospatial/ets-wms-client13/issues/27#issue-274510955

The methode
https://github.com/opengeospatial/ets-wms-client13/blob/d50b734706abdf002b3826623ffdd3dd2ff7b1fc/src/main/java/com/occamlab/te/spi/jaxrs/resources/wmsclient/TestMapResources.java#L105 should be invoked, but is not.

**Comment by lgoltz** [comment]
I'm using FF 57.0.4

**Comment by keshavnangare** [comment]
Fixed the Ajax request issue with FF.

Commit: 52af091

**Comment by lgoltz** [comment]
Tested locally with the fix https://github.com/opengeospatial/teamengine/pull/305.

Result view(s) looks like expected.
@keshav-nangare Can you create a pull request for the fix in the ETS?
