### ISSUE TITLE
Layer cite:Terrain not provided

### ISSUE THREAD

**Issue by lgoltz** [opengeospatial/ets-wms-client13#32]
Tested with QGIS 2.18.15 and Udig with the current SNAPSHOT of ETS WMS CLient 1.3 and TEAM Engine 4.10.

The layer `cite:Terrain` cannot be added in the client but is required to pass the tests.

**Comment by lgoltz** [comment]
Layer cite:Terrain is not listed in the capabilities of the proxy (e.g. http://localhost:8083/teamengine/monitor/3?REQUEST=GetCapabilities&SERVICE=WMS)

**Comment by lgoltz** [comment]
As far as I see the proxy wraps this service: http://cite.demo.opengeo.org:8080/geoserver_wms13/ows?service=WMS&request=GetCapabilities
The layer is missing there, too. 

I assume the missing layer must be added to the wrapped service. Or we have to remove the test from the ETS.

**Comment by lgoltz** [comment]
@bermud What do you think about that?

**Comment by bermud** [comment]
Remove it from the test if it is redundant and update the readme and possible the UI

**Comment by keshavnangare** [comment]
Fixed with this commit: ffb9d950159392acb9836d1c96b6d48431d52d4a [PR #36].

**Comment by lgoltz** [comment]
I've tested the branch locally with the current TEAM Engine (5.3-SNAPSHOT) with the docker environment. `cite:Terrain` is not longer listed as layer to add, but after stopping the test, the parent ('Perform GetMap request for all the layers') is still marked as failed.

@keshav-nangare Can you take a look at this?

**Comment by keshavnangare** [comment]
> I've tested the branch locally with the current TEAM Engine (5.3-SNAPSHOT) with the docker environment. cite:Terrain is not longer listed as layer to add, but after stopping the test, the parent ('Perform GetMap request for all the layers') is still marked as failed.


This issue is related to the teamengine so created the issue here: https://github.com/opengeospatial/teamengine/issues/333

**Comment by dstenger** [comment]
We can close this issue as soon as opengeospatial/teamengine#333 is solved.

**Comment by lgoltz** [comment]
Fix works fine with https://github.com/opengeospatial/teamengine/issues/333. 
Both PRs can be merged.
