### ISSUE TITLE
Test result always contains one failure although all tests were passed successfully

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ets-wms-client13#38]
Used software:
* TEAM Engine 5.3-SNAPSHOT (current master branch)
* WMS 1.3 Client Test Suite 1.4-SNAPSHOT (current master branch)

All tests are passed successfully (e.g. with QGIS).
Nevertheless, the ```Summary of results``` displays one failure.

![wms-client13-failure](https://user-images.githubusercontent.com/2989166/40053620-43639936-5842-11e8-8325-6cd79a04bc40.png)

**Comment by keshavnangare** [comment]
To fix this issue we have to update the coverage file from the teamengine-web app module, so the new issue create here: https://github.com/opengeospatial/teamengine/issues/344.
There is no change in ETS.

**Comment by dstenger** [comment]
Issue was fixed and tested in https://github.com/opengeospatial/teamengine/issues/344.
