### ISSUE TITLE
Test should report on the console the requests that are required to perform by the client

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wms-client13#4]
Steps:
1. When the test starts the test should tell the implementer what are the required requests, from the [overview page](http://htmlpreview.github.io/?https://github.com/opengeospatial/ets-wms-client13/blob/master/src/main/web/index.html). Maybe using checkboxes or other indicator.
   - [ ] GetCapabilities
   - [ ] GetMap with xyz...
   - [ ] GetFeatureInfo 
2. As the client starts interacting with the server, checkboxes should appear checked.
   - [x] GetCapabilities
   - [x] GetMap with xyz...
   - [ ] GetFeatureInfo  
3. The final report should show the tests that were not executed.

The dynamic page and results should look the following

![wms13client-result](https://cloud.githubusercontent.com/assets/3738898/4955678/09c1402a-6697-11e4-81c5-232f67bd3b97.jpg)

**Comment by bermud** [comment]
See related issue #3

**Comment by bermud** [comment]
You can use udig as a client to test the test suite: http://udig.refractions.net/

**Comment by bermud** [comment]
Completed nicely in the test server. 
However; I was not able to see the dynamic reporting when building locally the test. 
I tested with the latest TE : https://github.com/opengeospatial/teamengine/commit/13b8e3b2b34034cc81aa31848111e31b91bee1bd

After merging the fix and do some cleaning a new tag was created: 0.6.

**Comment by upendra-sachan** [comment]
There is issue comes after merging in wms-client13 in main.ctl file. I resolved it.

**Comment by bermud** [comment]
Closed in 0cec630cdcec1bad89d526e40f15b3a6c78a3474
