### ISSUE TITLE
Multiple layers that the test expects are missing in the test WMS service

### ISSUE THREAD

**Issue by vinnakota** [opengeospatial/ets-wms-client13#47]
WMS client test expects GetMap requests that target these 3 layers that are not advertised in the test WMS service. This is similar to issue #32 
* cite:Autos
* cite:BuildingCenters
* cite:Terrain

I also tested against TeamEngine Beta and it too has similar issue.

I tested using ArcMap, ArcGISPro, and ArcGIS Online MapViewer. In this case the client doesn't matter because the test is expecting to non-existent layers.

cc @ssankaran @BruceHarold

**Comment by dstenger** [comment]
Thank you for reporting.

@keshav-nangare Can you please check which layers are not supported any more by test WMS service (please also consider Prod and Beta environments)?

**Comment by keshavnangare** [comment]
Following is the test result of Beta environments:

We can see in below screenshot, as per the first comment the three layers are not advertised.
Ther service don't have these layers and the test suite is trying to process it. The `cite:Terrain`
layer was removed in the #32 issue and the PR is merged into master. But the Beta server & Prod server has the ets-wms-client13 version 1.3, this version doesn't have this change so the `cite:Terrain` layer is appearing in beta server.

Service is used in ets-wms-client13:
http://services.interactive-instruments.de/cite-xs-46/cite/cgi-bin/wms/wms/wms?request=GetCapabilities&version=1.3


Result:
![wms-client13-beta](https://user-images.githubusercontent.com/14732650/72531936-7eb1fe00-3898-11ea-939d-84a9d94de7ef.png)

**Comment by dstenger** [comment]
@keshav-nangare Can you please remove the layers `cite:Autos` and `cite:BuildingCenters` from the tests for now?

@ghobona Also, we should ask the maintainer of the service http://services.interactive-instruments.de/cite-xs-46/cite/cgi-bin/wms/wms/wms?request=GetCapabilities&version=1.3 about the stability.

**Comment by dstenger** [comment]
Issue created to host backend service by OGC: https://github.com/opengeospatial/ets-wms-client13/issues/48

**Comment by lgoltz** [comment]
see also: #46
