### ISSUE TITLE
Check that SERVICE is not Mandatory in GetMap request

### ISSUE THREAD

**Issue by bermud** [opengeospatial/ets-wms-client13#5]
chapter 7.2.2 and 7.2.3.3 say SERVICE is mandatory for GetCapa REQUESTs. (So the reference implementation is not strict)

But on GetMap SERVICE is not Mandatory (section 7.3.2)

**Comment by pepijnve** [comment]
OWS Common states that service is mandatory on all operations in 9.2.1 table 29 though.

**Comment by rjmartell** [comment]
The 'service' request parameter is not listed in Tables 8 or 9 (which specify the request parameters for `GetMap` and `GetFeatureInfo`, respectively). Since the WMS 1.3 spec does not depend on any other OGC spec, OWS Common constraints do not apply.

**Comment by bermud** [comment]
@upendra-sachan , Please check that the SERVICE parameter in the GetMap request  is **not** mandatory in the client test. Thank you!

**Comment by bermud** [comment]
@upendra-sachan Please verify that SERVICE parameter in the GetMap request is not mandatory.

**Comment by upendra-sachan** [comment]
Sure Luis.

I take this task as a priority task. And tomorrow itself I completed this.

Thanks.

---

Upendra Sachan
Mindstix Software Labs
http://www.mindstix.com

_Email:_ upendra.sachan@mindstix.com blah@mindstix.com
_Phone:_ +91 8446253174
_Skype:_ upendra.sachan1

**Comment by bermud** [comment]
Checked that is not mandatory
