### ISSUE TITLE
WMS client test mismatch between available layers and layers to be tested

### ISSUE THREAD

**Issue by robinhoutmeyers** [opengeospatial/ets-wms-client13#50]
The WMS client 1.3 test asks to request a numbers of WMS layers, but three of them do not appear in the capabilities of the WMS server:
- cite:Autos
- cite:BuildingCenters
- cite:Terrain

**Comment by dstenger** [comment]
@robinhoutmeyers Thank you for reporting. I transferred the issue to the ets-wms-client13 repository as your question targets that test suite.

@keshav-nangare Can you please take a look at the reported behavior?

**Comment by keshavnangare** [comment]
@dstenger 

The test suite has the same version on both beta and production environments. So these three layers are appearing in both environments. As service used by the wms-client test suite is not returning the above mentioned three layers and we have removed these layers in PR #49 and #36. The PR #49 changes are not merged yet so the layers are appearing in the test page.
If we merge these changes then layers will not appear anymore.

**Comment by dstenger** [comment]
@robinhoutmeyers 
Thank you for reporting.
However, this issue was already reported in #32 and #47.
I just merged all open pull requests and those fixes will be included in the next Beta release.
