### ISSUE TITLE
The WMS Client test server crashed after some time

### ISSUE THREAD

**Issue by robinhoutmeyers** [opengeospatial/ets-wms-client13#67]
While performing the WMS Client tests using one of our desktop clients, the server suddenly was no longer able to respond to GetMap requests and returned a HTTP 500 error for each subsequent GetMap request with the following error:

HTTP Status 500 – Internal Server Error
Type Exception Report

Message net.sf.saxon.trans.XPathException: DOMSender: no start node defined

Description The server encountered an unexpected condition that prevented it from fulfilling the request.

Exception

javax.servlet.ServletException: net.sf.saxon.trans.XPathException: DOMSender: no start node defined
	com.occamlab.te.web.MonitorServlet.process(MonitorServlet.java:276)
	com.occamlab.te.web.MonitorServlet.doGet(MonitorServlet.java:302)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
Root Cause

net.sf.saxon.trans.XPathException: DOMSender: no start node defined
	net.sf.saxon.dom.DOMSender.send(DOMSender.java:81)
	net.sf.saxon.dom.DOMObjectModel.sendSource(DOMObjectModel.java:112)
	net.sf.saxon.event.Sender.send(Sender.java:218)
	net.sf.saxon.IdentityTransformer.transform(IdentityTransformer.java:29)
	com.occamlab.te.web.MonitorServlet.process(MonitorServlet.java:235)
	com.occamlab.te.web.MonitorServlet.doGet(MonitorServlet.java:302)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:624)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:731)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

**Comment by dstenger** [comment]
Thank you for reporting.
Was this a temporary problem or are you still not able to test your client?

**Comment by robinhoutmeyers** [comment]
This appeared to be a temporary problem; when it happened, I tested for quite some time, but I have not yet been able to reproduce it.

**Comment by dstenger** [comment]
Thank you for confirming.
I propose to close this issue and reopen it if the problem occurs again.

**Comment by robinhoutmeyers** [comment]
OK
