### ISSUE TITLE
The WMS Client test does not put "Perform GetMap request for all the layers" on passed when all child tests have been passed

### ISSUE THREAD

**Issue by robinhoutmeyers** [opengeospatial/ets-wms-client13#68]
I executed the WMS Client test in combination with our desktop WMS client software based on LuciadLightspeed. It works and it seems all child tests have been passed, but the "Perform GetMap request for all the layers"  parent node seems to remain on the failed state.

Here is a screenshot of the test result:

![image](https://github.com/opengeospatial/ets-wms-client13/assets/11718993/8e8f23b2-c24d-4faa-868c-89a3af233207)

As you can see, all tests below "Perform GetMap request for all the layers" are passed, but the parent node remains failed. I can consistently reproduce this.

**Comment by dstenger** [comment]
Thank you for reporting.
I am also able to reproduce the behavior when testing with QGIS.
However, when finishing the test session and viewing the report, I cannot see any tracked failure. Thus, this just seems to be a display error.
Can you please check and confirm if this also applies to your use case?

**Comment by robinhoutmeyers** [comment]
Indeed! The summary of results doesn't shown any failure after finishing the test session and viewing the report; only the test overview this shows it as shown in my screenshot, but I guess this is not a problem to request compliancy.

**Comment by dstenger** [comment]
I agree, it should be no problem to request compliance.
However, I leave the issue open to further investigate why the display is not correct.

**Comment by robinhoutmeyers** [comment]
I also encountered a similar issue during a beta test for https://github.com/opengeospatial/ets-wms-client13/issues/66. Steps to reproduce:
* Start a WMS Client beta test session
* Open https://dev.luciad.com/portal/packed-samples/ria/dataformats/index.html?webgl&reference=epsg:4978
* Click on "Connect to..." and select "WMS"
* Fill in the proper GetCapabilities URL; e.g. (replace the number 33 with the actual number): https://cite.ogc.org/te2/monitor/33?REQUEST=GetCapabilities&SERVICE=WMS
* Click Next, select the Basic polygons layer and click Next again.

=> although the test session console and the test results (after stopping the test) will recognize the fact that a GetCapabilities and GetMap requests were received, the display during the test is never updated.

**Comment by ghobona** [comment]
@robinhoutmeyers Please note that since the issue is acknowledged as a bug in the ETS, you can proceed with submitting your product for compliance certification.

**Comment by robinhoutmeyers** [comment]
Noted, thanks!

**Comment by dstenger** [comment]
@robinhoutmeyers We created a pull request for the problem mentioned in the description of the issue.
However, the second issue reported [here](https://github.com/opengeospatial/ets-wms-client13/issues/68#issuecomment-1877974356) seems not to be related to the first one. Thus, we moved it to a separate issue: #73. We are already working on the new issue.
